# configs/config.yaml

# ===============================
# Model Configuration
# ===============================
model:
 window_size: 10
 feature_names:
   - temperature
   - vibration
   - pressure
   - operational_hours
   - efficiency_index
   - system_state
   - performance_score
 input_shape: [10, 7]
 architecture: "cnn_lstm"
 cnn_lstm:
   conv_filters: [64, 128]
   kernel_sizes: [3, 3]
   pool_sizes: [2, 2]
   lstm_units: [100, 50]
   dropout_rates: [0.3, 0.3, 0.3, 0.3]
   dense_units: 1
   activation: "sigmoid"

# ===============================
# Training Configuration
# ===============================
training:
 batch_size: 32
 learning_rate: 0.001
 epochs: 30
 validation_split: 0.2
 test_split: 0.1
 early_stopping_patience: 5

# ===============================
# PPO Configuration
# ===============================
ppo:
 enabled: true
 total_timesteps: 10000
 reward_weights:
   efficiency: 1.0
   satisfaction: 1.0
   safety: 1.0

# ===============================
# Path Configuration
# ===============================
paths:
 data_file: 'data/synthetic_sensor_data_with_anomalies.npz'
 results_dir: 'results'
 plot_config_path: 'configs/plot_config.yaml'
 reasoning_rules_path: 'src/reasoning/rules.pl'
 prob_log_rules_path: 'src/reasoning/prob_rules.pl'
 prob_log_rules_file: 'prob_rules.pl'
 prob_log_batch_script: 'src/reasoning/prob_log_batch.py'
 prob_log_save_script: 'src/reasoning/prob_log_save.py'
 knowledge_graphs_dir: 'results/knowledge_graphs'

# ===============================
# Symbolic Reasoning Configuration
# ===============================
symbolic_reasoning:
 enabled: true
 rules_path: 'src/reasoning/rules.pl'
 rule_extraction:
   confidence_threshold: 0.7
   min_support: 3
   max_rules: 100

# ===============================
# Knowledge Graph Configuration
# ===============================
knowledge_graph:
 enabled: true
 visualization:
   max_nodes: 100
   update_interval: 10
   node_types:
     sensor: '#lightblue'
     state: '#lightgreen'
     rule: '#lightpink'
     anomaly: '#salmon'
     insight: '#lightyellow'
   network_layout:
     type: 'spring'
     k: 1.0
     iterations: 50
 storage:
   format: 'png'
   save_interval: 10
   keep_history: 100

# ===============================
# ProbLog Configuration
# ===============================


# ===============================
# Reasoning Configuration
# ===============================
reasoning:
 rule_learning:
   base_threshold: 0.7
   window_size: 10
   min_confidence: 0.7
   thresholds:
     temperature:
       high: 80.0
       low: 40.0
       gradient: 10.0
     vibration:
       high: 55.0
       low: 20.0
       gradient: 5.0
     pressure:
       high: 40.0
       low: 20.0
       gradient: 2.0
     efficiency_index:
       high: 0.9
       low: 0.6
       gradient: 0.1
   pattern_detection:
     correlation_threshold: 0.8
     min_occurrences: 5
 prob_log:
   enabled: true
   python_interpreter: "python3"
   prob_log_script: "prob_log_interface.py"
   rules_file: "prob_rules.pl"
   thresholds:
     failure_risk: 0.5
     system_stress: 0.6
     efficiency_drop: 0.5
     overheating: 0.4
     maintenance_required: 0.3
   query_settings:
     batch_size: 100
     timeout: 30
